name: GitHub Actions Demo
run-name: ${{ github.actor }} teste github action
on:
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Name
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Print OS
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Print Branch and Repository
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Repository Cloned Message
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Print Workflow Ready Message
        run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Print Job Status
        run: echo "This job's status is ${{ job.status }}"
